# Generated by Django 3.0.4 on 2020-05-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice4',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
