# Generated by Django 3.0.4 on 2020-05-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_choiceanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoiceAnswer',
        ),
    ]
